[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["Joel Willoughby <jawilloughby68@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6.3"
syn = "0.15.26"
proc-macro2 = "0.4.21"

[lib]
proc_macro = true
proc_macro2 = true
